server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resource-server:

        jwt:
          issuer-uri: http://localhost:8080
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

jwt:
  secret: "U2VjcmV0S2V5Rm9ySldUMTU2NDg2NTQzMjEwOTg3NjU0MzIxMDk4NzY1NDMyCg=="
  token-validity-in-seconds: 86400
  expiration: 86400  # 24小时
  token-header: Authorization
  token-prefix: "Bearer "

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    filter: true
    persist-authorization: true

mybatis-plus:
  configuration:
    default-scripting-language: org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  type-handlers-package: com.example.handler  # 自定义JSON类型处理器
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.model.entity
